# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4d80ec23da68f5faa48348bad2d991a3a2815bcb505ea7124420e3242686b887d3ef86cc5d29096e8ed6cf6d42bceb650ba19f7ce5711cb321fcb6ce5a40dd05

test:
  secret_key_base: d1fb9c592442b0a831b59b8c1607ec466d07cf0cf28d279334c48e803a7bd9adb96decc140de1f04537e80c4bd7e124b7f1e493ec9aafc92ab9986e499912cc3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
